#ifdef PARAMETER_CLASS
#undef PARAMETER_CLASS
#endif
#ifdef S_PARAMETER_CLASS
#undef S_PARAMETER_CLASS
#endif
#ifdef STRING_PARAMETER_CLASS
#undef STRING_PARAMETER_CLASS
#endif
#ifdef MMS_CONFIG_VERSION
#undef MMS_CONFIG_VERSION
#endif
