# Common makefile for all makefiles.
# Must define MMSDIR in ALL makefiles before including this file, for example:
# MMSDIR = ../../.., do NOT add traling slash.

PYTHON_INCLUDE_PATH =$(KETLAER)/include/python$(PYTHON_VERSION)
PYTHON_CFLAGS=
PYTHON_LIB=-L$(KETLAER)/lib -lpython$(PYTHON_VERSION)
OBJS = $(SRCS:.cpp=.o)
